// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3nrtphSPSpsuTcPyB3-gpJpJ-hyMoN4',
    appId: '1:951897557228:web:754df2384cec1cc1b23dc9',
    messagingSenderId: '951897557228',
    projectId: 'portfolio-e0e22',
    authDomain: 'portfolio-e0e22.firebaseapp.com',
    storageBucket: 'portfolio-e0e22.firebasestorage.app',
    measurementId: 'G-8KBGPS73EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2kgu1sNckdrAYXyJ5_0aay7-RpDhtco',
    appId: '1:951897557228:android:a96aadc18e936706b23dc9',
    messagingSenderId: '951897557228',
    projectId: 'portfolio-e0e22',
    storageBucket: 'portfolio-e0e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7lKNBz_lVpx1QTFQyBCfM5ZWZ6Sl8EI',
    appId: '1:951897557228:ios:8ad06ca1b1dc53a4b23dc9',
    messagingSenderId: '951897557228',
    projectId: 'portfolio-e0e22',
    storageBucket: 'portfolio-e0e22.firebasestorage.app',
    iosBundleId: 'com.example.resumeBuilder',
  );
}
